apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: agent-backend-auth-secrets
  namespace: ia
spec:
  encryptedData:
    password-hash: AgAdgucWrx57caZgJwIcc/6w1Fd7Rsq7kgl4yrasZx9dJKL45nkJcAXBMRK7eS2eiElO0PVcF46WcMZY47SWEXDSZEw85UgvWfud3UWA14GVX1Qv7cT9TK9vNfnTUB17FWgT+5DZh/4wjYR10RbcJlElSEDJFibqepViYhaOqh7SyzDXw0jq6DYW29sI63KTghyWb9x6SJ21zT7/fCUAeYbi5NaBmBqZ/KW1YztC8OSk8mO5NL+OFybU48Y8kty9DgziUPbSoW833Tk96jzFHfGUqbtHCmpTnSpqEzRqxVdAKEnoaPn6cyNvztn39mHLtFrbFVlBn77X1dkL3KrZM4Gl5AlNxRK5a8HCxlNIJ7dL4zlIaqQR1EkhLftEodQlRldSjuGKOXpTo5mc9ZDZaFJ2U2NykcuZArQwjgYVTbsFNG+lbujL7FAm5aNDmAlEb5EgiUEBB/iL7K4jk0/zfxJwa8nAqSUPFV1sPvEgG3Aid3UGWdZe43Z/IUtcYAz9pgskv6+05KTHpWqVMeoY2G716oegSCM62r40Lp3pH/CRN4oTWo3pNFBvQa6CtxTPwEfnIg+EsXeNhlwlBJbYZr1w3Uf5C9CxwMx6cO8ULK5lZZVoL14XG3TBwkAhzlPosfjqGydWqBKFQ1FdPZ+ZJjxjXpza8MVMcuVljrLQF5hfU/pNIwoSojcA1vrV2UP5W9xogngX/rAgqM5D8vV2hEaHW2dDPBLN+s2BL25M0siTL/KAzRV857UCIeqtiOX1PtsEZC8h6EkSk1ZhSys=
    username: AgAsRN6vZQOHkkckh8KuKIM1Dn5KBzlUjEE3vQfUOYAfZXyCtBOjK3S6HQSH2S7MYcTnMR5jbGhD9dLRsosSP1QDsSbvN20E2rcfPNPiyuKH6P5a3VaTnnUUGhBIGnzneiBAgbI7e2UULUmLLdgZVAwv19Z/xdJhUdLVEcK8bi3UZ4VJtcXZ9XRid0Mh++Kw06yV7Cvi0SiU6EvXDkeDTMozXBv1yzl72aAGCPKsvQ5H5OmNWeOwnbvdUtujVyviBbCPU4oYbSdaYpicM19ncJdfvh+1op1Q+DVhyPUl/GuAZPqogsgHUdp8E9fvTcpotuKr8xMPeIn0NQ5doDE1ZE8v2SHzzP56Yp4Vxa5WPd9SEIWqAEJrg3ZPe3EYrjZ/XHfeySE3kgXfqEhh82LrDvBtc8t06TmMkZqgtP4aHqHYCjBr71pBa4UCA8H7gQ5O3JQlMXgsr2rpCgXMTkOcKiGPQsv5O4JGvpoy4mUUsMSztTgbCWhRT50dFEFIKPj6pUqWFTLXIHozCb2jsTC0qUAjYvqH/XoJqE6uEshqEGOqkNfEIAzF3JuCJLYYChJcJ6Bkq7AQzgGxoeSr12NtYyV/jGIn2S/EuWcmwBUCJV4iANUjFQfeM4XpAjA1Cy9jkGeXysJfZI2M1qHDyfkWDVRLci1FO+u7AZyvThmX5UscJxz2ye3Hur6PBWpns3whEjGhUQXzwsFkyZBArnSu
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: agent-backend-auth-secrets
      namespace: ia
    type: Opaque

