---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgres-secrets
  namespace: ia
spec:
  encryptedData:
    password: AgA2eH8qd5/ovtm5pVuJwPKUJgenKoMjx8uagCm2kepWGGM/2k/4UIYKcCsflXCwCMUSGZNhlIuWTHfhTygqz5Pk57fIekCgeewKsYPZ6SxIJW3IreOYmBJWx6SuyGpjqswYe2YaJMt9VwkXNabF99E9Y9bioQ2NLETTcy5sHLXH1JbY3flIMhQGI7y5rK0I2kBHPS6blIJS1NgHN873Hx7QkQWk/LjEw24v6V82C5vCaITaxhS/EOSBt7jI2FoArLsRfaIlmf+hEYZD2tNkXwwXg33yNfgNyhiat0IACGCpvpuVy47BFBZANrDWsyJg39LDqJioKpxigDSbQa36zN79wH5CYKbk72ozeXI31pcmM0kmUZB1P9pI8oHnXxLMsdV5sm28pDvqH+Z9xXTAg5fgtvZN251Jo2A+/bwgR7s5w1XQR7ckuiDJgmrDr4aMAY6Z+cVg+YzJ+EWMRjBvZp9D3wmL1GRIUBjIZP4K1FmqB4jEFzX9F/MKA8s1C9jCPE4bYvbENKLci9qd9xMPWT7Yqr4pDoIcOAaB3W5pPJhD6yFRtCtr1L97a/mKM2GhEpgZCsM3ESh91vs5vSDCiSSJi1hWdgrCZeR89OPXagDBzJMfzfIZkQermQ3RUB2wKwgq3C6Axg994DU6FVRPBmwkVNRocYeXs6tiS0cClJLRXzdbeCl4RCSFHEVcGHyKzK9SUlhvJkZm76Bz
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgres-secrets
      namespace: ia
    type: Opaque
