apiVersion: v1
kind: Secret
metadata:
  name: agent-backend-auth-secrets
  namespace: ia
type: Opaque
stringData:
  username: "REPLACE_ME"
  password-hash: "REPLACE_ME"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: ia
type: Opaque
stringData:
  password: "REPLACE_ME"
