---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: agent-backend-auth-secrets
  namespace: ia
spec:
  encryptedData:
    password-hash: AgCg5JJTfx4h8L+1HoPMBxZK+l8KKJQvd9me4w4lPDGir+x0tINoRBQBtBFdDNswoM6GZwFL7Dx0YT3f0/0Xoy/XUhfL0vniViFMDW8JUXIO/hVAD2X7CKIU5Bl57HuS2zYDcuodg8C/TIMrDbQZK9jzU1k2nvsT/3ml143ZMh199X2pWoPQrK5qgxkvWUp6ctgaSuVsg2a3QTiTHLENavWcixWl/RJURn3fUNFYJj1BUwP1aAh2abiF1juz1wl7CoRgqOyBkZLdhGzKRtVjys/pW3JhVAeHSSoZBgyVdsOqmRTNgUzkTz2KnPXRqPmvYqUiZ4/C2WjBrKzxN7/82s8W1LyVPVWnfnEhUUiWpMZrhfjGVPMm9bRDY3p1O+TtHzyo/j8scYTwnb6bZTQ00OAE71N5R8luz4w76SpWQwZwAT2dGhsEV2rmEbpr1bOXFlohwuOoVF+2ucy60Kyp4AVqrfLMu2xVMG74OlaSs5Ft80sogZyQTeECpfbVY4+o/KMa8mImBc+rQ1Laje2ok8qbvxegmU2qT5wIDvuXhPG20voSnIWYFQblSdXxjdjNxUEk69+9b71VMLNx85vrpvFkfdzUfUu+bV5fShCwpyVsmaHm3AppUkNnqRigeK7FrPeGpCTwo205kzZ1hGCEz6llo1WKyiKjeu1UzIBmYuorh+E+T7PJ22rnR9q14yrbScn0fYGk5oX15vXp26EezRmhqx5mdDmKLaLKj8TjSWSbGwk6Tm4JBmU72w6jzdCdIflwwV7yjAXDNJCw4YM=
    totp-secret: AgB9sPS7BwTbP1SXrF+KNzE5sGTIJc3c+uduC1X4qcTV5K32HF545sNHmMp1r52erhuchu65igE604VdBMkDQMwpSZQSowHNSssvB71nAwkVzXvxnujmMOr4wVxITi5c6tvvFVcuxJkSe8M5gbI8qX5eVWbbarHPhWLSxD8rjiFhoTgM5wU3+NEI0ge8BVCLgrVV/lgvJ7bqKIn3Xx2G4eQvtwchPuQvNC72jwQwwHUxvFvaJJ74XWxQ2bljCmVblncGj09MBi4lNh13N/lhva35rWsi8P5+KMw8UjhNnkWve79AxrCNsltphCPZPhaERapPzTfxaNuB9XRqQu6xaOzSSQGUB1gSHVnkQEpZkzVUOLDas9/cfsMfQoA98f36tFX+v4KhHV9/XHpZGT8/4rL8KLtmKPFY2t1uKpNeHHHBp330AKfFwr38YqckcqgratJtQM/t/aKqPRuV4uaCV0tJtcCnCNMkcmu2Ymmb9XO2inyH2hGoDLRYRAHlMNwjZ9jYPKvcncZzdcAEUJ8h6AMXYiQxvFQrwXXTsVo/NO5QQu1oICQzkQK7HXXjdU3MrIlDpd1/Q1md5GPDkPY49vUvGQ7il10eguiTlO2l0hwp1EpcFQiYKRBbBkwe/WJ2ivvvjSy7Kw4XfoVD2EeMfTyuZcoNnzSiRdCo5zqAwtuvWbnVF9i7d64bim789CPwLvks+xYyT8iYL4DLcmgW3npP
    username: AgBisodY0JUXWYPGSpygfAZ8VUmgMnWuHCggLUBpavLUoFcuIOvZzTZBKgapAgBfoZK8B1XcIrbXoYXZeME09nI1Aa1ZOQhaGNbgv8HDrO07LiQr6EroPGSJZeREYphdIcP17Po2of7T0ZCF/mT3xvWot1ULhspeXMeKk0dWxlsX4W0EZ9+8spGybzH1BRww8fENejpkfbInE2BcyXgKaXoMylSlifMulqIyeT20bJdYDGMzl4moQtfdMyOzcT0hLJEBZ5SJu1rg2GI4aW3/le0Rb2jRF4uag8c297cfEBahpZpCFLNWb5rhBkAl8BXFttpB+RTOutGNyDJlbUZVMNq00adUsOIQlWmNp8hZp8gHBWTPcNkWk6cCMuSUhYtNNhIcSnhK+lbAk2My0lLbjA29jSn9nG9Yole99J1JKK2xSQGnL3oo0A194tx20HMAu17s7n9TRExHNBOwr0AoJ6SJdfLxSOu2mJvpsyLJRCDTsgpLwO63P5SOkZw76arfiKfYM+CVLy5ZXCJXVBkcK3NsOO34J4U1qgAlcjA19BBYrRlZ6jSr+eobUlP4qYg0djpy3w+wqPk4FNCFfJXKajA2VzaRbi378TaZqxO8/dJsJl66y0AwtR/zIZ8Hx9CdCjWvG/dsZGg/tG/qTehKWicL5pFkQVF5Kuz0FvYadqJQxUCkbXJNZBExArdXU6A/qzxZCvIAsdH2IHctXKUF
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: agent-backend-auth-secrets
      namespace: ia
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgres-secrets
  namespace: ia
spec:
  encryptedData:
    password: AgA2eH8qd5/ovtm5pVuJwPKUJgenKoMjx8uagCm2kepWGGM/2k/4UIYKcCsflXCwCMUSGZNhlIuWTHfhTygqz5Pk57fIekCgeewKsYPZ6SxIJW3IreOYmBJWx6SuyGpjqswYe2YaJMt9VwkXNabF99E9Y9bioQ2NLETTcy5sHLXH1JbY3flIMhQGI7y5rK0I2kBHPS6blIJS1NgHN873Hx7QkQWk/LjEw24v6V82C5vCaITaxhS/EOSBt7jI2FoArLsRfaIlmf+hEYZD2tNkXwwXg33yNfgNyhiat0IACGCpvpuVy47BFBZANrDWsyJg39LDqJioKpxigDSbQa36zN79wH5CYKbk72ozeXI31pcmM0kmUZB1P9pI8oHnXxLMsdV5sm28pDvqH+Z9xXTAg5fgtvZN251Jo2A+/bwgR7s5w1XQR7ckuiDJgmrDr4aMAY6Z+cVg+YzJ+EWMRjBvZp9D3wmL1GRIUBjIZP4K1FmqB4jEFzX9F/MKA8s1C9jCPE4bYvbENKLci9qd9xMPWT7Yqr4pDoIcOAaB3W5pPJhD6yFRtCtr1L97a/mKM2GhEpgZCsM3ESh91vs5vSDCiSSJi1hWdgrCZeR89OPXagDBzJMfzfIZkQermQ3RUB2wKwgq3C6Axg994DU6FVRPBmwkVNRocYeXs6tiS0cClJLRXzdbeCl4RCSFHEVcGHyKzK9SUlhvJkZm76Bz
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgres-secrets
      namespace: ia
    type: Opaque
